version: '3.8'

networks:
  laravel:

services:
  nginx:
    image: library/nginx:stable-alpine
    container_name: backend-assessment-nginx
    volumes:
      - ./src/app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8060:80"
    depends_on:
      - php
     
    networks:
      - laravel
  
 
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-assessment-php
    volumes:
      - ./src/app:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel